### ISSUE TITLE
Event: error retry?

### ISSUE THREAD

**Issue by jesseproudman** [bnielsen1965/wska#2]
Per the docs, WebSocketKeepAlive can have errors that bubble up like so:

https://github.com/bnielsen1965/wska#event-error

It looks like if a child web socket gets an error, that error is passed up to this main callback as well. Will those errors result in a retry of the socket?

Thanks!

**Comment by bnielsen1965** [comment]
> Will those errors result in a retry of the socket?

You mean a reconnect?

There are only two cases where a reconnect will occur...
1) If a failure occurs in creating a new WebSocket, https://github.com/bnielsen1965/wska/blob/master/index.js#L47

2) If a currently open WebSocket closes for any reason, https://github.com/bnielsen1965/wska/blob/master/index.js#L77

If an error on a currently open WebSocket causes the socket to close then it will reconnect. The error will also be emitted by wska, so you will see the error if you have a listener.

However, if an error occurs on an open WebSocket but it does not cause the socket to close then it will not reconnect as it is assumed the connection is still open. This error will also be emitted by wska.

**Comment by bnielsen1965** [comment]
@jesseproudman Did that answer your question? And does the current method of handling errors and reconnects have issues in a specific case?

**Comment by jesseproudman** [comment]
Thanks. 

If I understand correct, all errors detected on the Websocket itself will be passed up to the WSKA error listener as well. The error my WSKA error listener picked up was `Error: read ECONNRESET`. It appears in that case, itre-opened the connection.

**Comment by bnielsen1965** [comment]
Correct, it should pass on all errors.

I think it should retry the connection for that error (ECONNRESET), but was it connected and working when you received that error? I think error commonly occurs when the server on the other end cannot open the connection because there is no service listening on the port or it is blocked by the firewall.

**Comment by jesseproudman** [comment]
I'll add additional instrumentation to confirm it's working as expected.

Thanks for the prompt responses. I really appreciate it!
